name: dev
on:
  push:
    paths:
      - 'environments/dev.tfvars'
  workflow_dispatch:
    inputs:
      do_init:     { type: boolean, default: true,  description: "Run terraform init?" }
      do_fmt:      { type: boolean, default: false, description: "Run terraform fmt?" }
      do_validate: { type: boolean, default: true,  description: "Run terraform validate?" }
      do_plan:     { type: boolean, default: true,  description: "Run terraform plan?" }
      do_apply:    { type: boolean, default: false, description: "Run terraform apply?" }
      do_destroy:  { type: boolean, default: false, description: "Run terraform destroy?" }

permissions:
  contents: read
  id-token: write

jobs:
  call:
    uses: ./.github/workflows/terraform-multi.yml
    with:
      environment: dev
      tfvars_file: environments/dev.tfvars
      rgname: ritkargs
      saname: ritkasas
      scname: ritkascs
      key: dev.tfstate

      runInit:     ${{ github.event_name == 'workflow_dispatch' && inputs.do_init     || false  }}
      runFmt:      ${{ github.event_name == 'workflow_dispatch' && inputs.do_fmt      || false }}
      runValidate: ${{ github.event_name == 'workflow_dispatch' && inputs.do_validate || false  }}
      runPlan:     ${{ github.event_name == 'workflow_dispatch' && inputs.do_plan     || false }}
      runApply:    ${{ github.event_name == 'workflow_dispatch' && inputs.do_apply    || false }}
      runDestroy:  ${{ github.event_name == 'workflow_dispatch' && inputs.do_destroy  || false }}

      # runInit:     ${{ inputs.do_init    || true  }}
      # runFmt:      ${{ inputs.do_fmt     || false }}
      # runValidate: ${{ inputs.do_validate|| false  }}
      # runPlan:     ${{ inputs.do_plan    || false  }}
      # runApply:    ${{ inputs.do_apply   || false }}
      # runDestroy:  ${{ inputs.do_destroy || false }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
