name: prod

on:
  push:
    paths:
      - 'environments/prod.tfvars'
  workflow_dispatch:
    inputs:
      do_init:                 { type: boolean, default: false,  description: "Run terraform init?" }
      use_environment_init:    { type: boolean, default: false,   description: "Require environment approval for init?" }
      do_fmt:                  { type: boolean, default: false,  description: "Run terraform fmt?" }
      do_validate:             { type: boolean, default: false,  description: "Run terraform validate?" }
      do_plan:                 { type: boolean, default: false,  description: "Run terraform plan?" }
      do_apply:                { type: boolean, default: false, description: "Run terraform apply?" }
      do_destroy:              { type: boolean, default: false, description: "Run terraform destroy?" }

      
      use_environment_apply:   { type: boolean, default: false,  description: "Require environment approval for apply?" }
      use_environment_destroy: { type: boolean, default: false,  description: "Require environment approval for destroy?" }

permissions:
  contents: read
  id-token: write

concurrency:
  group: prod-tf
  cancel-in-progress: false

jobs:
  call:
    uses: ./.github/workflows/terraform-multi.yml
    with:
      environment:  prod
      tfvars_file:  environments/prod.tfvars
      rgname:       ritkargs
      saname:       ritkasas
      scname:       ritkascs
      key:          prod.tfstate
      
      # Run toggles
      runInit:     ${{ github.event_name == 'push' || inputs.do_init }}
      runFmt:      ${{ github.event_name == 'push' || inputs.do_fmt }}
      runValidate: ${{ github.event_name == 'push' || inputs.do_validate }}
      runPlan:     ${{ github.event_name == 'push' || inputs.do_plan }}
      runApply:    ${{ github.event_name == 'push' || inputs.do_apply }}
      # runDestroy:  ${{ inputs.do_destroy }}

      # Approval toggles (separate)
      useEnvironmentInit:    ${{ github.event_name == 'push' || inputs.use_environment_init }}
      useEnvironmentApply:   ${{ github.event_name == 'push' || inputs.use_environment_apply }}
      # useEnvironmentDestroy: ${{ inputs.use_environment_destroy }}

    secrets:
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
