name: prod

on:
  push:
    branches:
      - main
    paths:
      - 'environments/prod.tfvars'

  workflow_dispatch:
    inputs:
      do_init:              { type: boolean, default: false,  description: "Run terraform init + fmt + validate?" }
      do_plan:              { type: boolean, default: false,  description: "Run terraform plan?" }
      do_apply:             { type: boolean, default: false, description: "Run terraform apply?" }
      do_destroy:           { type: boolean, default: false, description: "Run terraform destroy?" }

      use_environment_init:    { type: boolean, default: false, description: "Require approval before Init?" }
      use_environment_plan:    { type: boolean, default: false, description: "Require approval before Plan?" }
      use_environment_apply:   { type: boolean, default: false,  description: "Require approval before Apply?" }
      use_environment_destroy: { type: boolean, default: false, description: "Require approval before Destroy?" }

permissions:
  contents: read
  id-token: write

concurrency:
  group: prod-tf
  cancel-in-progress: false

jobs:
  call:
    uses: ./.github/workflows/terraform-multi.yml
    with:
      environment:  prod
      tfvars_file:  environments/prod.tfvars
      rgname:       ritkargs
      saname:       ritkasas
      scname:       ritkascs
      key:          prod.tfstate

      # Run toggles
      runInit:     ${{ github.event_name == 'push' || inputs.do_init }}
      runPlan:     ${{ github.event_name == 'push' || inputs.do_plan }}
      runApply:    ${{ github.event_name == 'push' || inputs.do_apply }}
      runDestroy:  ${{ github.event_name == 'workflow_dispatch' && inputs.do_destroy }}

      # Approval toggles
      useEnvironmentInit:    ${{ github.event_name == 'workflow_dispatch' && inputs.use_environment_init }}
      useEnvironmentPlan:    ${{ github.event_name == 'workflow_dispatch' && inputs.use_environment_plan }}
      useEnvironmentApply:   ${{ github.event_name == 'push' || inputs.use_environment_apply }}
      useEnvironmentDestroy: ${{ github.event_name == 'workflow_dispatch' && inputs.use_environment_destroy }}

    secrets:
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
